agent:

  id: AGENT-001

  name: Poste-Test

  version: 1.0.0


server:

  protocol: https

  host: api.smart-siem.strife-cyber.org     #192.168.1.110  #169.254.170.76     #192.168.1.198                

  port: 443  #8000

  api:

    ping: "/health"

    heartbeat: "/api/v1/heartbeat"

    logs: "/api/v1/logs/ingest"

    ws_commands: "/api/v1/agents/ws"

    command_result: "/api/v1/commands/{command_id}/result"

    block_ip : "/action/block-ip"

    disable_user : "/action/disable-user"

    isolate_host : "/action/isolate-host"

  timeout: 10

  verify_ssl: false


authentication:

  token: ""


heartbeat:

  enabled: true

  interval: 30


logging:

  level: INFO

  file: logs/agent.log

  max_size: 10485760      # 10 Mo

  backup_count: 5

  console: true


collectors:

  logs: true

  cpu: true

  memory: true

  process: true

  network: true

  filesystem: true

  services: true



logs:

  paths:

    linux:
      - /var/log/syslog
      - /var/log/auth.log

    windows:
      - "C:\\Windows\\System32\\winevt\\Logs\\Application.evtx"
      - "C:\\Windows\\System32\\winevt\\Logs\\System.evtx"
      - C:\Windows\System32\winevt\Logs\Security.evtx
      #- "D:\\Promo X2028\\X3\\Projet Intégrateur\\Realisation\\Projet-Int-grateur-Smart-SIEM\\Agents\\agent\\logs\\test.log"

  read_from_end: true



cpu:

  interval: 10

  alert_threshold: 300


memory:

  interval: 10

  alert_threshold: 300


process:
  interval: 15

  top_processes: 300


network:
  interval: 30

  max_connections: 300


services:
  interval: 60

  max_services: 300

  monitor_only_critical: true

  critical:

    windows:

      - WinDefend
      - EventLog
      - W32Time
      - TermService

    linux:

      - ssh.service
      - apache2.service
      - nginx.service
      - mysql.service
      - docker.service
      - filebeat.service


filesystem:
  interval: 60

  watch:
    windows:
      - C:\Users
      - C:\ProgramData

    linux:
      - /home
      - /etc
      - /var/log

  ignore:
      - __pycache__
      - node_modules
      - .git
      - temp

  disk_usage_threshold: 300



sync:  #pour la syncronisation des logs local avec le serveur après retablissement de la connexion

  enabled: true

  interval: 15

  batch_size: 100

  max_retry: 5

  delete_after_sync: true



commands:

  enabled: true

  interval: 5

  acknowledge: true

  max_per_poll: 20



tls:

  enabled: false

  verify_server: false

  certificate: certs/agent.crt

  private_key: certs/agent.key

  ca_certificate: certs/ca.crt


